---

- hosts: localhost
  roles: # Write ip:mac pairs to redis database.
    - render

- hosts: dhcp_server
  tasks:
    - copy:
        src: "{{ item }}"
        dest: "/etc/ansible_test/"
      with_fileglob:
        - "conf/*"
