---
  - name: Load var ip inventory
    include_vars: ip_inventory.yml

  - name: Get IP MAC records from REDIS
    register: records
    anchor_redis:
      db: 0
      command: hgetall
      key:  dhcpipmac

  - name: render
    template:
      src: VLAN_conf.j2
      dest: conf/VLAN{{ item }}_dhcp.conf
    with_items: "{{ VLAN }}"
