---
  - name: Get IP MAC records from REDIS
    register: records
    anchor_redis:
      db: 0
      command: getall

  - name: render
    template:
      src: VLAN_conf.j2
      dest: conf/VLAN{{ item }}.conf
    with_items: "{{ VLAN }}"
