---
  - name: Load var ip inventory
    include_vars: ip_inventory.yml

  - name: Get ready for render entries 
    register: records
    render_entry:
      inventory: "{{reserved_m_ip}}"

  - name: render
    template:
      src: VLAN_conf.j2
      dest: conf/VLAN{{ item }}_dhcp.conf
    with_items: "{{ VLAN }}"
