---
- include: updateFacts.yml
  when:
    - "'updateFacts' in taskname"
- include: updateMacip_linsol.yml
  when:
    - "'updateMacip_linsol' in taskname"
- include: updateMacip_vmware.yml
  when:
    - "'updateMacip_vmware' in taskname"
- include: updateArpscan.yml
  when:
    - "'updateArpscan' in taskname"
